os: linux

language: shell

branches:
  only:
    - main

services:
  - docker

env:
  global:
    - DOCKERHUB="quietsy/heimdall-monitor-mod"

jobs:
  include:
    - stage: BuildImage
      if: (NOT (type IN (pull_request)))
      script:
        - docker build --no-cache -t ${DOCKERHUB}:${TRAVIS_COMMIT} .
        - docker tag ${DOCKERHUB}:${TRAVIS_COMMIT} ${DOCKERHUB}:latest
        - echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin
        - docker push ${DOCKERHUB}:${TRAVIS_COMMIT}
        - docker push ${DOCKERHUB}:latest