#!/usr/bin/with-contenv bash

if [ ! -d /config/monitor ]; then
  git clone https://github.com/quietsy/heimdall-monitor.git /config/monitor
  ln -s /config/monitor /var/www/localhost/heimdall/storage/app/public/monitor
  rm -f /etc/php7/php-fpm.d/www.conf
  mv /config/monitor/www.conf /etc/php7/php-fpm.d/www.conf
else
  echo "Monitor already installed, skipping"
fi