#!/usr/bin/with-contenv bash

if [ ! -d /config/monitor ]; then
  git clone https://github.com/quietsy/heimdall-monitor.git /config/monitor
  ln -s /config/monitor /var/www/localhost/heimdall/storage/app/public/monitor
  cp /config/php/www2.conf /config/php/www2.conf.backup
  grep -q '^clear_env' /config/php/www2.conf && sed -i 's/^clear_env.*/clear_env=no/' /config/php/www2.conf || echo 'clear_env=no' >> /config/php/www2.conf
  mv /config/nginx/site-confs/default /config/nginx/default.backup
  mv /config/monitor/default /config/nginx/site-confs/default
  /etc/cont-init.d/20-config
  s6-svc -r /run/s6/services/php-fpm
  s6-svc -r /run/s6/services/nginx
else
  echo "Monitor already installed, skipping"
fi